#!/usr/bin/env python3
"""Regenerate the runtime's terrain text from the same authored catalogue."""
import json
from pathlib import Path
from describe_world import finish
from room_catalogue import TERRAIN, REALM_FORESTS, TRANSIT
from indoor_rooms import CATALOGUE_PATH

ROOT = Path(__file__).resolve().parents[1]

def render():
    lines = ['// Generated by tools/generate_room_defaults.py from the editorial catalogues.',
             '#ifndef HAVEN_ROOM_DEFAULT_TEXT_H', '#define HAVEN_ROOM_DEFAULT_TEXT_H',
             'static const char *const room_terrain_text[] = {']
    for i in range(33):
        lines.append('  '+json.dumps(finish(TERRAIN[i]).replace('\n', '\n\r'))+',')
    lines += ['};', 'static const char *const room_realm_forest_text[] = {']
    for name in ('otherfor.are', 'godfor.are', 'wildfor.are', 'hellfor.are'):
        lines.append('  '+json.dumps(finish(REALM_FORESTS[name]).replace('\n', '\n\r'))+',')
    lines += ['};', 'static const char *const room_transit_text[] = {']
    for prose in TRANSIT:
        lines.append('  '+json.dumps(finish(prose).replace('\n', '\n\r'))+',')
    lines += ['};', 'static const char *const room_taxi_text[] = {']
    taxis = json.loads(CATALOGUE_PATH.read_text(encoding='utf-8'))['taxi_defaults']
    assert len(taxis) == 100 and len(set(taxis)) == 100
    for prose in taxis:
        lines.append('  '+json.dumps(finish(prose).replace('\n', '\n\r'))+',')
    lines += ['};', '#endif', '']
    return '\n'.join(lines)

if __name__ == '__main__':
    (ROOT/'src'/'room_default_text.h').write_text(render())
