"""Authored room vocabulary shared by the area migration and C++ terrain fallback.

No exits are inferred from names. Furniture described by a place is implemented
as a P record, not as an object, shop, container, or equipment provider.
"""

TERRAIN = {
0: "Small chips freckle the bare walls, and a pale outline follows the floor where something once stood. Every scrape of a shoe sounds distinct in the unfurnished space. There's little here to soften a voice or conceal a movement.",
1: "Old repairs stitch the `wroad`x in crooked bands of tar. Traffic has ground the pavement smooth through the middle, leaving a crumble of grit along the edges. A faint rubber smell clings to the surface; weeds have taken root in cracks too narrow for a tire to reach.",
2: 'The plaster carries a scatter of old nail holes and the faint shadows of furnishings moved long ago. Underfoot, the floor has been rubbed smooth by familiar journeys across the room. A modest sofa rests in a comfortable corner, the upholstery carrying a faint trace of fabric and furniture polish.',
3: "Dark finishes frame a broad `wdance floor`x, the surface crosshatched with heel marks. A low sofa rests against the wall, where upholstery holds a trace of spilled drinks and old perfume. It's a room built for noise; even a few voices can fill the open middle.",
4: "Dining tables stand close enough for neighboring conversations to mingle. Chair backs shine where hands have caught them, and little crescents of wear mark the floor beneath each setting. The air carries a lingering trace of cooked food and wiped surfaces, the familiar aftermath of a busy meal.",
5: 'Rows of displays make narrow aisles through a patchwork of labels and packaging. At the `wcounter`x, countless small transactions have polished a dull sheen into the edge. The shop smells of cardboard and handled goods, with dust tucked into corners beyond the reach of an ordinary sweep.',
6: "A long `wbar counter`x wears a dark gloss where generations of elbows have rested. Old drink rings overlap like faint stamps in the finish. `wTables`x stand farther back, close enough for company to lean together over the lingering smells of stale beer, wood polish, and something sweet spilled long ago.",
7: "The `walley`x squeezes between hard walls streaked by old runoff. Grit and scraps collect where the paving meets the masonry, out of reach of passing feet. Sound comes back short and sharp here, and the close air holds a damp, mineral smell beneath a trace of old refuse.",
8: "Steel beams cross above a broad industrial floor scarred by dragging loads. Rust blooms around bolts, and old handling marks run out beneath the open spans. The warehouse smells of concrete dust and worked metal; a small noise can travel a surprising distance before the structure gives it back.",
9: "Scuffs stripe the lower walls of this practical commercial interior. The floor has a faint waxy smell, with dull patches where shoes have worried away the finish. Broad working spaces and undecorated corners leave the room feeling ready for the next shift to begin.",
10: "Uneven swathes of `ggrass`x spread across the open ground, fine blades mingling with coarse clumps and brittle seed heads. Fallen stems form a tawny thatch close to the soil. There's a green, earthy smell wherever the growth has been pressed down, and little shelter among the low plants.",
11: "Rough `wstonework`x closes around the tunnel, the joints darkened by moisture. Pale mineral traces creep down the walls above a fringe of grit. Each footfall acquires a second, hollow edge in the confined passage, while the air tastes faintly of damp stone.",
12: "A lingering smell of coffee settles over the cafe's small `wtables`x. Cup rings interrupt the finish, and chair legs have worn little fans into the floor. The `wcounter`x faces this comfortable clutter, with a smooth patch along the edge where people pause to talk before finding a seat.",
13: "The `wroof`x spreads in a patchwork of weathered seams and older repairs. Grit gathers against raised edges, and little blisters roughen the exposed surface. Up here the building offers few sheltered corners; noises from below arrive thinned by the open air.",
14: "The basement smells of settled dust and the cool mineral damp of buried walls. Heavy foundations crowd the edges of a plain floor, their seams traced with pale deposits. Small sounds carry beneath the low ceiling, making the weight of the building overhead seem very close.",
15: "Pale, washable surfaces give the clinical space a scrubbed, unforgiving clarity. The sharp smell of antiseptic lingers around the fittings, and even the scuffs look washed. `wWaiting chairs`x line the margin of the clear floor, their practical arrangement offering little distraction from the business of being here.",
16: "Repeated polishing has left a dull shine on the public floor. Restrained trim and substantial walls lend the interior the patient gravity of an institution. Wear gathers where visitors pause, a quiet record of waiting feet beneath the otherwise formal finish.",
17: "The vehicle's `wseats`x fit snugly inside a close metal shell. Seams in the upholstery hold a fine dust, and the enclosed air smells of fabric, rubber, and old journeys. There's just enough space to settle in, with every nearby surface shaped around the demands of travel.",
18: "Open `cair`x falls away in every direction. Without a wall or a patch of ground close at hand, distances become difficult to judge; even a small movement makes the surrounding emptiness apparent. It's an exposed place, with nothing nearby to break the immense sweep of the sky.",
19: "The `rhellgate`x cuts a raw outline through the surrounding space. Cracked ground crowds the threshold, the edges looking scorched even where no flame touches them. A bitter, iron-like tang hangs close to the opening. Beyond that hard rim, distance refuses to settle into any comfortable shape.",
20: "Overlapping folds of `cwater`x stretch across the open expanse, breaking every reflection into fragments. Small ripples vanish into broader swells before an eye can follow them far. Beneath the restless surface, depth keeps a darker color; there's no solid footing here.",
21: "Fine particles drift through the `bsubmerged water`x like dust in a room without walls. Nearer shapes keep their edges for a moment, then dissolve into blue-green distance. Sound loses direction in the enveloping water, and the world beyond the surface feels impossibly remote.",
22: "An immense reach of `cupper air`x opens around this height. The ground has become a distant arrangement of shapes, stripped of familiar scale. Nothing encloses the exposed space; it's all depth and distance, with the vast curve of the sky swallowing the smallest movement.",
23: "`gTree trunks`x rise through a deep litter of leaves, their bark rough with lichen. Roots knuckle out of the soil and disappear beneath fallen branches. The woodland smells of leaf mold and old rain; beyond the nearest tangle, overlapping growth breaks the view into narrow, uncertain glimpses.",
24: "Ridges of `wrock`x fold around the cave like the grain of some immense, broken shell. Grit crunches among loose chips, and dark seams trace the walls where moisture has found a way through. The air carries the cold, chalky smell of stone long sheltered from the weather.",
25: "Black water gathers between the roots of the `gswamp`x, filmed at the edges with green scum. Coarse growth hides patches of mud that bear the soft impressions of older disturbances. The air smells thickly of wet earth and rotting leaves, and every apparently firm patch ends in another uncertain margin.",
26: "Loose `ysand`x lies in low ridges, scattered with shell chips worn smooth as old teeth. Coarser grains scratch underfoot while the finer sand gives way and settles again. Faint tracks lose definition at the edges, leaving the exposed beach with a surface that never quite keeps a mark.",
27: "Broken `wstone`x shoulders through thin pockets of grit. Fractured faces show a fresher color beneath the weathered crust, and small shards lie trapped in the cracks. The ground offers a succession of awkward footholds, each rough outcrop interrupting the next.",
28: "`cShallow water`x wrinkles over a bed of pale sediment. The bottom remains visible in patches, then blurs where fine silt hangs in the water. Every disturbance loosens another soft cloud from the submerged ground, briefly hiding the little ridges beneath the surface.",
29: "The `wsidewalk`x is worn smooth along the line of passing feet. Fine cracks branch through the paving, packed with grit and the occasional stubborn weed. Old stains mottle the less-traveled edges; it's a narrow strip of everyday ground, carrying years of small, hurried journeys.",
30: "Faded bay markings divide the parking lot into crooked-looking rectangles. Tires have laid dark arcs across older repairs, and gritty deposits collect along the margins. The open pavement carries a faint petroleum smell, with little weeds breaking through where the surface has begun to surrender.",
31: "Rows of `wgrave markers`x rise from ground softened by roots and time. Lichen freckles the older stones, blurring carved letters into shallow scratches. Grass presses close around each base. The measured gaps between the graves give even a short walk the unhurried rhythm of counting names.",
32: "Passing feet have pressed the `yearth`x into a hard, uneven skin. Small stones sit embedded like blunt teeth, while looser soil gathers in shallow hollows along the margins. Broken stems and old impressions mark the places where the traveled ground begins to give way.",
}

REALM_FORESTS = {
'otherfor.are': "Ancient `gtrees`x lift twisted crowns above moss thick enough to swallow a footprint. Leaves curl into unfamiliar shapes, showing pale undersides like the backs of small hands. A sweet, bruised-green scent hangs among the roots. It's almost a familiar woodland, until the eye tries to name a single thing growing here.",
'godfor.are': "Clean-limbed `gtrees`x stand above soft grass, each crown given exactly enough room to spread. Flowers grow in drifts that seem unplanned until their colors repeat farther between the trunks. The air smells faintly of blossom. Even the fallen leaves rest with an unsettling grace, as though decay has been asked to be beautiful.",
'wildfor.are': "Massive `gtrunks`x thrust through a snarl of vines and broad, ragged leaves. Roots heave the soil into ridges, swallowing fallen timber under fresh growth. The air is rich with sap and wet bark. Nothing here yields much room: branch, creeper, and thorn press together in a slow, relentless struggle for space.",
'hellfor.are': "Knotted `wtrees`x claw across one another above a litter of brittle splinters. Burls bulge from the bark in shapes almost like faces, their features lost whenever the angle changes. A dry, bitter smell catches in the throat. Between the trunks, the cramped gaps look less like paths than places where something has forced a passage.",
}

TRANSIT = [
    "Scuffed panels enclose the subway carriage, their seams holding a fine black dust. Metal handholds line the narrow aisle above a row of `wseats`x polished by countless passengers. The close air smells of warm rubber and old upholstery; it's a small, hard-sided pocket of the city.",
    "A narrow `wseat`x leaves the riding position open to the surrounding air. Wear has smoothed the saddle, with dust caught along the stitched seams. There's little between the rider and the wider world, and every small shift brings the compact frame close at hand.",
    "A thin `yforest path`x winds among trunks furred with lichen. Passing feet have exposed roots beneath the leaf litter, polishing their crowns to a dull sheen. Broken twigs catch along the margins, where undergrowth leans back toward the narrow strip of earth as though waiting to reclaim it.",
]

# Ordered by room function, before the broader sector classification.
# (pattern, prose, place keyword + description pairs)
RULES = []
def rule(pattern, prose, *places):
    RULES.append((pattern, prose, list(places)))

rule(r'underwater|submerged|under (?:the )?(?:ocean|water|waves)|watery depths', TERRAIN[21])
rule(r'\b(?:skies|sky|atmosphere|treetops)\b|^above (?:the arena|cage|magical)', TERRAIN[18])
rule(r'\b(?:roof|rooftop)\b|atop a covered walkway', TERRAIN[13])
rule(r'\b(?:sidewalk|pavement)\b', TERRAIN[29])
rule(r'parking|carport', TERRAIN[30])
rule(r'\b(?:alley|alleyway)\b', TERRAIN[7])
rule(r'\b(?:outside|before|exterior|front of|behind a .*store|window front|outskirts)\b', "Old runoff has traced narrow stains down the building's lower walls. Underfoot, the approach is scuffed pale where people stop before moving on. Grit gathers close to the foundation, and the surrounding structure gives this small patch of ground a little shelter from the wider world.")
rule(r'\b(?:stairs|staircase|stairwell|steps|landing|wooden stair|fire.escape)\b', 'Countless climbs have hollowed the treads and polished the edges of the stairs. Dust gathers in the angles beyond the reach of a shoe. A small landing interrupts the ascent, offering a level pause where nearby movement sounds unusually close against the enclosing structure.')
rule(r'\b(?:hallways?|corridors?|passageways?|entry corridor|office corridor)\b', "Foot traffic has worn a dull ribbon down the corridor's floor. Along the walls, old scuffs and small repairs show beneath an otherwise plain finish. The passage gives every step a little extra reach, carrying the sound ahead through the close, undecorated space.")
rule(r'\b(?:walkway|footpath|pathway|trail|path|promenade)\b', "A narrow path traces the ground, pressed smooth through the middle and crumbling at the edges. Tiny stones and broken stems collect in the shallow hollows. It's an unassuming route, marked less by careful construction than by the steady insistence of people passing through.")
rule(r'\b(?:streets?|avenue|highway|road|lane|parkway|boulevard|drive|row)\b|crossroads|intersection', TERRAIN[1])
rule(r'\b(?:lawns?|grassy|grass|meadow|fields?|grounds|yard|perimeter)\b', TERRAIN[10])
rule(r'\b(?:gardens?|greenhouse|biodome|arboretum)\b', 'Leaves overlap above carefully worked soil, their shapes ranging from fine, feathered sprays to broad green blades. The planting beds carry a rich smell of damp earth and bruised stems. Small weeds test the borders of the cultivated ground, softening the neat divisions wherever tending has missed a corner.')
rule(r'\b(?:forest|woods|wood|jungle|grove)\b', TERRAIN[23])
rule(r'\b(?:beach|shore|shoreline|sands|dunes)\b', TERRAIN[26])
rule(r'\b(?:ocean|bay|river|lake|pond|water|waters|sea|moat|lagoon|reservoir|shallows)\b', TERRAIN[20])
rule(r'\b(?:bluffs|cliff|cliffs|mountains|mountain|peaks|rocky|headlands)\b', TERRAIN[27])
rule(r'\b(?:cemetery|cemetary|graveyard)\b', TERRAIN[31])
rule(r'\b(?:swamp|swamps|bog|mire)\b', TERRAIN[25])
rule(r'\b(?:tunnel|tunnels|sewer|sewers|catacombs)\b', TERRAIN[11])
rule(r'\b(?:cave|cavern|grotto|crevice)\b', TERRAIN[24])
rule(r'\b(?:empty|unfurnished|bare|featureless|vacant|undesignated|development|construction|renovations|transition|delete|test)\b', "Bare surfaces expose every scrape and uneven patch in this unfinished space. Fine dust settles along the floor's margins, beyond the clearest stretch of standing room. With no furnishings to break it up, the enclosure gives a single voice an unexpectedly hollow sound.")
rule(r'bathroom|restroom|washroom|lavatory|lavatories|toilets|outhouse', 'The washroom smells faintly of soap and mineral damp. A screened `wshower`x occupies one side, with pale water marks beneath the fittings and a drain set into the washable floor. Small scratches cloud the surfaces nearest the washing space, evidence of cleaning as much as use.', ('shower', 'Pale mineral trails mark the shower fittings above the drained washing space. Water patters against the floor beneath the spray, and the close air carries a clean trace of soap.'))
rule(r'shower|steam room', 'Pale mineral traces fan out beneath the `wshower`x fittings. The washable floor slopes gently toward drainage grooves, their edges dark against the surrounding surface. Soap leaves a clean, faintly sweet trace in the damp air, while every movement carries clearly within the close washing space.', ('shower', 'Pale mineral trails mark the shower fittings above the drained washing space. Water patters against the floor beneath the spray, and the close air carries a clean trace of soap.'))
rule(r'locker|changing room|dressing room|changing booth|costumery', 'A narrow `wbench`x runs beside the changing space, the seat rubbed smooth by years of hurried arrivals. Clothing has left a faint fabric smell in the close air. Scuff marks gather beneath the bench, while the middle of the floor remains clear enough to change without bumping into the fittings.', ('bench', "The bench offers a firm seat, the most-used stretch worn smoother than the ends. Small nicks catch along the edge. It's a straightforward place to sit shoulder to shoulder without crowding the open floor."))
rule(r'bedroom|bedchamber|sleeping|guestroom|guest room|guest suite|residential suite|hotel.*room|motel room|bunk|dormitory|quarters|barracks|^room [0-9]|^(?:kingson|queenson|bishop|rook) [0-9]', 'Soft creases and the faint smell of laundered fabric distinguish the sleeping area from the rest of the room. Wear gathers around the furniture, tracing familiar steps across the floor. A `wbed`x occupies the quieter half, the creased bedding softening the room around a place to rest or talk in low voices.', ('bed', 'The mattress yields beneath creased bedding, with a firmer edge for sitting beside someone. Soft fabric muffles small movements, bringing a quiet conversation within reach of the pillows.'))
rule(r'kitchen|kitchenette|prep area|canteen|mess hall', 'Fine knife marks cloud the `wprep counter`x, overlapping older stains that scrubbing has never quite lifted. The kitchen carries a settled smell of cooking beneath a sharper trace of soap. Work surfaces hug the walls, leaving the center open for the small, repeated journeys of preparing a meal.', ('prep counter', "Knife marks crisscross the preparation surface, fading beneath older stains. The clear edge leaves room for company to examine the work together, with the counter separating careful hands from the kitchen's busier floor."))
rule(r'pantry|larder|freezer|cold goods|refrigerated', 'Close ranks of shelves surround a narrow strip of floor. Dust outlines the spaces between stored supplies, and the shelf edges are nicked from things being lifted in and out. The enclosed air holds a faint, dry packaging smell, lending the room the patient stillness of provisions waiting to be needed.')
rule(r'living room|living space|living area|lounge|parlor|parlour|common room|recreation|\bden\b', "A cushioned `wsofa`x faces a low table. The cushions have softened into familiar hollows, and faint cup marks interrupt the table's finish. Fabric dulls the sound of movement, giving the room a comfortable intimacy that suits an unhurried conversation.", ('sofa', "Deep cushions settle into familiar hollows along the sofa. The arms are rubbed smooth, and the upholstery holds a faint fabric warmth; there's room to sit close or claim a comfortable corner."))
rule(r'dining|restaurant|resteraunt|diner|cafeteria|banquet', "Tables break the dining room into little pockets of company. Chair backs shine from handling, and older meal-time mishaps survive as faint marks beneath the wiped surfaces. A `wcorner table`x sits just beyond the main arrangement, close enough to catch the room's conversation without being caught in the middle of it.", ('corner table', 'The corner table sits beyond the busiest line through the room. Chairs tuck close around a surface marked by faint rings and tiny scratches, making a comfortable pocket for an unhurried conversation.'))
rule(r'cafe|coffee|doughnut|tea party', TERRAIN[12], ('counter', "The counter's edge has been polished smooth by resting hands. Small scratches cloud the top, leaving a comfortable shared surface for leaning in to talk or examining something laid between companions."), ('tables', 'Chairs draw close around the table edges, their backs polished by handling. Faint cup rings remain beneath the wiped finish, giving each small gathering a surface to share and a little distance from neighboring company.'))
rule(r'\bbar\b|tavern|pub|saloon|hookah', TERRAIN[6], ('bar', "Old drink rings overlap in the bar's dark finish. The edge is smooth beneath an elbow, and the long shared counter brings neighboring patrons within easy reach of a remark or a quietly exchanged confidence."), ('tables', 'Chairs draw close around the table edges, their backs polished by handling. Faint cup rings remain beneath the wiped finish, giving each small gathering a surface to share and a little distance from neighboring company.'))
rule(r'counter|checkout|check.in|prescription|food counter|concession', 'The `wcounter`x has a smooth, familiar edge, polished by resting hands. Below it, shoe marks darken the floor where people pause to wait. The surface divides the room at the height of an ordinary conversation, with a few stubborn scratches recording the business passed back and forth across it.', ('counter', "The counter's edge has been polished smooth by resting hands. Small scratches cloud the top, leaving a comfortable shared surface for leaning in to talk or examining something laid between companions."))
rule(r'office|study|chambers|command center', "A `wdesk`x faces the visitor's chair across a modest patch of floor. Fine scratches catch along the working edge, and the room carries a dry trace of paper and furniture polish. Even the surrounding storage seems arranged to bring a conversation back to the person behind that broad surface.", ('desk', "The working edge of the desk is smooth beneath the hands, with fine scratches crossing the surface. A visitor's chair faces it at an easy speaking distance, leaving the desktop between the two sides of a conversation."))
rule(r'meeting|conference|council|senate|court room|audience chamber', "Chairs gather around a substantial `wmeeting table`x, their spacing setting a measured rhythm along the edge. Faint rings and small dents survive in the finish. There's room to stand behind the seated company, though the room's arrangement draws every glance back toward the middle.", ('meeting table', 'Chairs gather around the long tabletop, their spacing keeping each face in view. Faint rings interrupt the finish. Leaning forward closes the distance across the table; sitting back leaves a more formal gap.'))
rule(r'foyer|lobby|reception|entry hall|entryway|entrance hall', 'The busiest line across the reception floor has been worn to a dull sheen. A `wwaiting bench`x rests against the wall, with seats softened by brief visits and long delays. The clear center gives arrivals a moment to take in the room before joining anyone already settled along the edge.', ('waiting bench', 'The bench has a smooth seat and a back marked by the rub of countless coats. From here, arrivals remain in view while the busiest line across the floor passes a little farther away.'))
rule(r'entrance|entry|front walk|back door|cellar door|exit to', "Repeated passage has smoothed the threshold into a shallow, familiar dip. Dust catches along the edges where the surrounding structure meets the ground. It's a small transition space, carrying the scuffs of arrivals, departures, and people who stopped here to finish a conversation.")
rule(r'library|bookstore|book store|stacks|shelves|reading|archives|obscure titles', 'Book spines crowd the shelves in uneven bands of faded color. The air smells of dry paper and old bindings, with a faint mustiness tucked deeper between the rows. A `wreading table`x offers a clear island among the accumulated pages, the surface rubbed smooth where readers have leaned over their work.', ('reading table', 'Broad enough for open books, the table keeps a clear working surface among the shelves. Fine scratches and a dull polish mark the places where readers have leaned, with chairs close enough to compare a passage in low voices.'))
rule(r'classroom|lesson|humanities|supernatural history|latin room|forensics|training and development', 'Student desks face the teaching area in rows made imperfect by small shifts and worn legs. Faint scratches survive on the desktops, a second curriculum of idle marks. The `wfront desk`x sits in plain view; the `wrear desks`x offer a little distance from the focus of the lesson.', ('front desk', 'The nearest student desk faces the teaching space without an intervening row. Scratches cloud the desktop, and the close position leaves every raised hand plainly in view.'), ('rear desks', 'These desks sit behind the nearer rows, with scratches and idle marks surviving on the working surfaces. The position offers a view over the other seats and a little distance from the teaching area.'))
rule(r'laboratory|labratory|\blab\b|experimentation|experiments|diagnostics|quality assurance', 'The laboratory smells faintly sharp from repeatedly cleaned surfaces. Small abrasions cloud the `wworkbench`x where careful work has met stubborn materials. Stations stand apart around a clear floor, and the sparse surroundings give each stain or misplaced speck a significance it would lose in an ordinary room.', ('workbench', 'Fine tool marks cross the stout working surface, with dust caught in the deepest cuts. The bench stands at a practical height for leaning over a piece of work, bringing careful hands and curious company together.'))
rule(r'clinic|hospital|medical|recovery|diagnosis|examination|reparative|radiology|intervention|rehabilitation|wellness|ward', TERRAIN[15], ('waiting chairs', 'A row of practical chairs faces into the room. Their edges bear small scuffs from bags and restless hands, and the gaps between them allow a quiet exchange without leaning into the main thoroughfare.'))
rule(r'cell|prison|dungeon|holding pen|cage', "Hard boundaries press close around a small patch of floor. A `wbench`x stands along one edge, the surface scratched and rubbed smooth by restless use. There's little here to occupy an eye: a seam, an old mark, the same corners again. Even a quiet movement seems to fill the enclosure.", ('bench', "The bench offers a firm seat, the most-used stretch worn smoother than the ends. Small nicks catch along the edge. It's a straightforward place to sit shoulder to shoulder without crowding the open floor."))
rule(r'chapel|church|cathedral|temple|shrine|ritual', 'Stone and wood enclose a focus of worship, their worn surfaces lending weight to the empty floor before it. Fine dust lies in the deeper joints, beyond the reach of ordinary tending. The arrangement encourages stillness, and the smallest scrape sounds intrusive in the surrounding hush.')
rule(r'confession', "Worn wood closes around a narrow `wseat`x and the partition before it. The grain has darkened where hands have rested, making small islands of gloss in the dull finish. It's a space scaled to a lowered voice, with scarcely room for a gesture larger than the conversation.", ('seat', 'The narrow seat fits close within the enclosing woodwork. The edge has been rubbed smooth, while the partition ahead brings the space down to a lowered voice and a small, private exchange.'))
rule(r'theatre|theater|auditorium|amphitheater|concert hall|coliseum', 'Rows of `waudience seats`x turn toward the performance space. Fabric and old polish lend the room a familiar backstage smell, while wear along the seat edges records a history of shifting spectators. The open space ahead seems to hold a pause, waiting for the first movement to make sense of all those watching places.', ('audience seats', 'The seats face the performance space in close rows. Fabric softens the small sounds of settling in, while worn armrests mark where earlier audiences have waited, watched, and leaned toward their companions.'))
rule(r'stage|dance floor|dance studio|ballroom|mosh pit|rehearsal', "Heel marks and fine scratches cross the broad `wperformance floor`x. Repeated movement has worn a softer sheen into the busiest patches, leaving the margins comparatively dull. Along the floor edge, there's room to watch without entering the open space where every gesture becomes conspicuous.")
rule(r'bleachers|dugout|pews|seating|picnic', 'Rows of `wseats`x share a view across the gathering space. Hands have polished the edges, and the ground beneath bears the restless marks of feet. Sitting here puts company shoulder to shoulder, with little gaps beside the rows for those who would rather remain standing.', ('seats', 'The seats share a clear view, their nearest edges smoothed by repeated use. Small scuffs mark the space below, while sitting shoulder to shoulder brings conversation comfortably close.'))
rule(r'gym|fitness|weight room|dojo|fencing|arena|dueling|fighting pit|shooting range|archery', 'Repeated practice has left scuffs and worn patches across the open `wtraining area`x. The most traveled lines overlap until individual movements become a history of effort on the ground. The sidelines offer room to watch, close enough to follow the action without crowding the central space.')
rule(r'pool', 'Water gathers in a defined basin, small ripples breaking the surface into shifting pieces. Pale deposits mark the hard `wbasin rim`x where wet surfaces have dried again and again. The surrounding ground feels close to the water, with the rim offering a clear place to pause beside it.', ('basin rim', "The basin's hard rim is smooth along the top, with faint mineral traces where splashes have dried. Leaning here brings the water close enough to follow the small ripples breaking against the edge."))
rule(r'porch|porche|patio|terrace|veranda|balcony|deck', "Weather has roughened the platform's exposed surfaces, picking out seams and small cracks. The open floor lies close to the supporting structure, with worn patches where people have lingered. It's a modest extension of the building, open enough for outside sounds to arrive without much interruption.")
rule(r'warehouse|steel mill|shipping|container|loading dock|hangar', TERRAIN[8])
rule(r'workshop|workroom|work area|atelier|artist|painting|kiln|sewing|engineering|design studio', 'Scratches and old stains overlap across a broad `wworktable`x. Fine dust has found the joints of the surrounding work surfaces, surviving even a conscientious cleanup. The workshop smells faintly of handled materials, and the clear spaces between stations make room for the patient business of making and mending.', ('worktable', 'A broad working surface bears fine cuts, stains, and older repairs. The edge is rubbed smooth where people lean over a project, with enough room for companions to examine the same detail from either side.'))
rule(r'computer|digital media|recording|music room|photo lab|filming|radio room|dj booth', "Cables follow the edges of closely arranged workstations. Handling has polished the working surfaces, leaving duller outlines around the fixed equipment. A `wworkstation`x faces into the setup, placing company close enough to examine the same work amid the room's dry, faintly electrical smell.", ('workstation', 'A chair draws up to the equipment surface, with cables tucked along the back. The nearest edge is worn smooth by hands and sleeves, leaving a compact position for concentrating on the work or sharing a closer look.'))
rule(r'laundry|laundromat', 'A clean, powdery smell of detergent hangs over the laundry fixtures. Lint gathers in narrow seams despite the hard, washable surroundings. The `wfolding counter`x offers a broad pause beside the washing area, with a smooth edge suited to sorting fabric or lingering over the ordinary business of the day.', ('folding counter', 'The broad counter smells faintly of clean fabric and detergent. The finish is smooth enough for folding, with a long clear edge where companions can lean while sorting a load or sharing the latest gossip.'))
rule(r'storage|stockroom|storeroom|closet|shed|back room|utility|supply|maintenance', 'Scuffed shelves border a narrow working space. Their edges carry chips from awkward loads, and fine dust marks corners that seldom see a hand. The room has the close, dry smell of things put aside, with a clear strip of floor keeping the stored supplies within reach.')
rule(r'basement|cellar|celler', TERRAIN[14])
rule(r'\bshop\b|store|market|bazaar|bizaar|display|department|apparel|clothing|fashion|jewelry|jewelers|jewellery|novelt|accessories|supplies|aisles|pharmacy', TERRAIN[5], ('counter', "The counter's edge has been polished smooth by resting hands. Small scratches cloud the top, leaving a comfortable shared surface for leaning in to talk or examining something laid between companions."))
rule(r'house|home|apartment|cottage|cabana|chalet|residence|lodgings|inn|hotel|motel', TERRAIN[2], ('sofa', "Deep cushions settle into familiar hollows along the sofa. The arms are rubbed smooth, and the upholstery holds a faint fabric warmth; there's room to sit close or claim a comfortable corner."))
rule(r'\btent\b|teepee|yurt|encampment|camp|lean.to', 'Fabric and rough supports enclose the camp center, keeping the gathering space close to the ground. Small creases and patched seams record earlier use of the shelter. The air carries the smells of canvas and earth, and the whole arrangement has the intimate scale of a temporary refuge.')
rule(r'void|nothingness|abyss|no end|dreamheart|rift|between times|dreamscapes|memories|genesis|creation|^age of', "Distance gathers around a small point of orientation, then loosens before it becomes a recognizable place. The edges of the `cspace`x have the wavering certainty of a remembered room. It's difficult to hold any one detail in view for long; something about the surroundings always seems to have just changed.")
rule(r'bridge|pier|boardwalk|dock|quay', 'A weathered span carries a worn line of passage above the supporting structure. Grit catches in the repeated joints, and small chips expose fresher material beneath the surface. The open footing gives nearby sounds room to travel, leaving the crossing feeling more exposed than the ground it connects.')
rule(r'\bwell\b(?!-)|fountain', 'Hands and weather have smoothed the upper edge of a `wstone rim`x. Farther down, the masonry keeps a rougher grain, with pale traces caught in the joints. The boundary invites a pause beside the feature, close enough to follow the little imperfections across the worn surface.', ('stone rim', 'The upper stone is broad and smoothed by weather and handling, cool against a resting palm. Shallow pits interrupt the worn edge, with room to lean together beside the masonry and look over the rim.'))
rule(r'plaza|square|courtyard|court|town center|city center|central hub', 'Hard ground opens into a broad public gathering space. Old repairs interrupt the surface, and the busiest patches have been worn smooth by crossing feet. Along the margins, small groups can find a little enclosure while the open center leaves every arrival plainly visible.')
rule(r'elevator|airlock', 'Close panels surround a small standing space, their repeated seams giving the compartment a precise, cramped shape. Fine scuffs cluster at shoulder and shoe height. The hard surfaces catch every rustle and breath, making even a brief pause feel separate from the larger structure around it.')
rule(r'ladder|crane|catwalk', 'Metal joints and narrow footing define this exposed framework. Rust catches around the fastenings, and the most handled edges show a brighter wear beneath the dull surface. With little room to move aside, every change of position brings the construction and the drop beyond it sharply into view.')
rule(r'boat|aboard|ship|sloop|freighter|ketch|airplane|\bbus\b|\btaxi\b|\btrain\b', 'A close structural shell encloses the passenger space. Repeated joints and fitted panels leave few wasted corners, their edges scuffed by the awkward business of settling in. The interior carries the stale fabric smell of travel, bringing nearby company within easy reach of a quiet conversation.')

# Material and layout cues are used only when the room name supplies them.
TRAITS = [
(r'brick', 'Exposed brick shows fine variations in color and worn mortar seams.'),
(r'marble|marbled', 'Pale veins cross the marble surfaces, breaking their polished finish into subtle patterns.'),
(r'wood.panel|oaken|oak accents', 'Wood paneling gives the surrounding surfaces a close, warm grain.'),
(r'tile|tiled', 'Tile joints divide the hard surfaces into a regular pattern.'),
(r'skylight|skylit', 'Glazing overhead breaks the ceiling into framed sections.'),
(r'sunken', 'The recessed central floor gives the room a distinct lower gathering space.'),
(r'cramped|small|tiny|claustrophobic', 'The close proportions leave little spare space between the room\'s edges.'),
(r'large|spacious|expansive|enormous|grand', 'Broad proportions give the central space room to breathe.'),
(r'rundown|run.down|dilapidated|grungy|filthy|squalor|grime|neglected|shabby', 'Grime and worn finishes have settled into the less-used corners.'),
(r'pristine|clean|tidy|renovated', 'Careful upkeep shows in the clean edges and orderly surfaces.'),
(r'graffiti', 'Layered graffiti crowds the exposed surfaces, old marks half-covered by newer ones.'),
(r'glass|glazed', 'Glass panels give the surrounding structure a reflective, layered appearance.'),
(r'fenced|fence', 'A fence establishes a definite boundary along the edge of the space.'),
(r'rock garden', 'Small stones lie arranged among patches of low planting.'),
]

# These signatures distinguish named establishments without claiming that
# adjoining rooms, merchandise transactions, or equipment are accessible.
THEMES = {
"brawling brothers": "Old dents pit the pub's stout woodwork; the furnishings look accustomed to surviving an argument.",
"nymph's rest": "Dark trim and theatrical upholstery lend the Nymph's Rest the close, perfumed atmosphere of a confidence shared backstage.",
"succubus club": 'Wine-red upholstery presses against dark finishes, with perfume caught in the fabric like the trace of an earlier visitor.',
"starlight lounge": 'Small stars scatter across the dark trim, their pale points lending the lounge a touch of carefully manufactured night.',
"house red": 'Wine-colored accents and substantial woodwork give House Red the faded richness of a room that expects good manners.',
"pigment and paper": "Paint has dried in bright freckles along the studio's edges, and the air carries a dry trace of paper.",
"black rose book": 'Rose motifs curl along dark shelf trim, while old bindings lend the bookshop a faintly musty sweetness.',
"collateral damage": 'Heavy counters and blunt metal fittings give the gun-and-pawn premises the guarded air of a business used to appraising strangers.',
"moore for less": 'Pale pharmacy finishes and tightly ordered labels lend Moore for Less a scrubbed, practical neatness.',
"el mercado del mundo": "Overlapping patterns crowd the market's trim, their clashing colors giving the shared space a cheerful, improvised warmth.",
"davedash": 'Bright shelf edges and tightly packed labels make DaveDash a small riot of everyday promises in colorful packaging.',
"studio splendente": 'Carefully spaced displays and crisply finished trim give Studio Splendente the poised air of an outfit awaiting a final adjustment.',
"studio luisant": 'Fine trim and subtle decorative flourishes lend Studio Luisant a fashionable restraint, with little allowed to look accidental.',
"fertile valley": "The florist's working edges hold the green smell of clipped stems, with tiny leaf fragments caught in the seams.",
"rosie's diner": "Chrome and familiar upholstery lend Rosie's the comfortable shine of a diner polished through years of ordinary meals.",
"oh, for heaven's cake": 'Soft bakery colors and a lingering sweet flour smell lend the cafe the gentle fussiness of a carefully iced cake.',
"dionysus": "Bottle motifs repeat along dark shelf trim, surrounding the liquor store's neatly framed displays like a quiet invitation.",
"nate's nugs": "Leaf motifs wander across the decor, giving Nate's Nugs the relaxed finish of a place in no particular hurry.",
"pleasure chest": 'Playful packaging colors peek between discreet display divisions, making the Pleasure Chest equal parts coy and conspicuous.',
"unveiled costumes": "Layers of fabric jostle against theatrical details, and a faint powdery smell clings to the costume shop's crowded fittings.",
"fragrant tree": "A dry ribbon of incense scent clings to the Fragrant Tree's wood and paper, outlasting the smoke that left it.",
"knead to relax": 'Muted colors and soft finishes give the treatment rooms a hush reinforced by the faint scent of clean linens.',
"the playhouse": "Theatrical red accents warm the Playhouse's woodwork, carrying a hint of stage ceremony into the more ordinary corners.",
"paine performance": 'Hard-wearing fittings show the small knocks of a performance building, where even the polished edges have seen hurried hands.',
"little nishiki": 'Fine wood grain and restrained decorative panels give Little Nishiki a quiet, carefully balanced rhythm.',
"petite cuisine": "Closely arranged furnishings give Petite Cuisine an intimate scale, with the decor kept small enough to share the table's attention.",
"giovanni": 'Warm woodwork carries the familiar sheen of an Italian dining room kept welcoming through countless meals.',
"gravesend hardware": 'Heavy shelving and chipped industrial trim lend Gravesend Hardware the dry, practical smell of metal, dust, and useful things.',
"hook, line": 'Fishing motifs mingle with durable coastal fittings, their rubbed edges giving the shop an unpretentious waterfront character.',
"hunt & hook": 'Outdoor-trade displays and rugged fittings give Hunt & Hook the solid, slightly dusty air of equipment awaiting a journey.',
"savage talent": 'Acoustic finishes and performance imagery give Savage Talent a close studio feel, softening the room around the work of being heard.',
"cortex academy of civic integration": "Cortex Academy of Civic Integration's pale finishes meet in meticulously kept seams, a clinical neatness that leaves even a small scuff conspicuous.",
"mandala": 'Fine geometric motifs repeat between the jewelry displays, their precise little patterns echoing the care of the settings.',
"old world jewel": 'Traditional wood trim frames small jewelry displays with the patient precision of an old-fashioned craft bench.',
"stellar": 'Crisp display lines and sharply contrasting finishes give Stellar an air of being dressed for inspection.',
"hometown diner": "Nostalgic trim and softened furniture edges give the Hometown Diner the easy familiarity of a regular customer's seat.",
"loving kitchen": 'Plain furnishings show careful upkeep, their worn edges lending the Loving Kitchen a practical, communal warmth.',
"beelzebubbles": "Irreverent decoration crowds the laundromat's scuffed fittings, and detergent gives the clutter a surprisingly wholesome smell.",
"howl at the moon": 'Gothic flourishes curl through the dark woodwork, giving Howl at the Moon a theatrical fondness for the night.',
"cafe salerno": 'Warm finishes and close furnishings bring Cafe Salerno down to the comfortable distance of a conversation over a cup.',
"the retreat": "Game and costume motifs fill the Retreat's decor with small invitations to imagine being somewhere, or someone, else.",
"museum": "Restrained finishes leave the museum's displays room to command attention, with quiet gaps between each carefully arranged subject.",
"aboard": 'Ribbed bulkheads and inset panels crowd the shipboard space, their seams holding the faint, stubborn smell of enclosed travel.',
"castle hearts": 'Heart motifs recur in exaggerated fittings, lending Castle Hearts the sugary grandeur of a storybook drawn slightly out of scale.',
"new hope": 'Austere finishes meet in disciplined lines, giving New Hope the carefully maintained appearance of a settlement with rules for everything.',
}

EXACT = {}
def exact(name, prose, *places):
    EXACT[name.casefold()] = (prose, list(places))

exact('The World Storehouse', 'Broad storage bays recede across a plain floor, their unadorned surfaces giving this repository a scale beyond any ordinary shop. The open floor is kept clear among the bays.')
exact('The Dreamheart', "The dream folds inward around a `cpale, wavering center`x. Half-formed colors gather there and slip apart, like memories losing the names of the people in them. Nothing quite becomes a wall or a horizon. It's the still point of an unfinished thought, with all the surrounding strangeness leaning toward it.")
exact('Yggdrasil', 'The `gWorld Tree`x rises beyond any comfortable measure of height. Roots shoulder out of the earth like wooded ridges, their bark furrowed deeply enough to hold whole drifts of fallen leaves. Above, the branches divide and divide again until the crown resembles another landscape, suspended beyond reach.')
exact('the steel mill', 'Heavy steel framing spans broad industrial floors. Repeated supports and worn concrete divide the mill into immense working bays, with rust collecting at joints and handling scars crossing the open ground.')
exact('the Cortex Academy of Civic Integration Biodome', 'Curving structural ribs divide the biodome enclosure above cultivated ground. Beds of vegetation occupy the space within the framework, their irregular leaves set against the deliberate geometry of the `wdomed shell`x.')
exact('Cortex Academy of Civic Integration Biodome', EXACT['the cortex academy of civic integration biodome'][0])
exact('Moore Woods', 'Old leaves lie thick beneath the `gtrees of Moore Woods`x, their dry upper layers hiding dark, crumbling mold. Lichen mottles the trunks above a tangle of roots and fallen limbs. The view closes after only a little distance, broken into strips of bark and the soft clutter of growth.')
exact("Warden's Wood", "Close ranks of old `gtrees`x enclose Warden's Wood. Roots push through the leaf litter like the knuckles of buried hands, and moss softens the fallen timber between them. The woodland smells of damp bark. Every gap opens onto another trunk, giving the forest a watchfulness that never quite resolves into a watcher.")
exact('Deadwood', 'Pale, broken limbs crowd the dark floor of `wDeadwood`x. Standing trunks shed strips of weathered bark, exposing grain the color of old bone. Splinters catch in the leaf litter, and the dry smell of decaying timber hangs between the trees. New growth threads quietly through what the older woodland has left behind.')
exact('Blackmoon Woods', 'Dark trunks crowd the tangled ground of `gBlackmoon Woods`x. Roots vanish beneath thorny growth and rise again a few paces farther on, making the forest floor difficult to read. Overlapping branches divide the distance into deep pockets. The air smells of leaf mold, with a bitter trace from bruised green stems.')
exact('Arkwright Cemetery', 'Lichen freckles the `wheadstones`x of Arkwright Cemetery, filling the shallow cuts of weathered names. Grass presses against the bases, and older markers lean by almost imperceptible degrees. The rows keep a solemn order despite the slow work of roots and time, leaving measured spaces for the living to pass between the dead.')
exact('the Arkwright Mausoleum', 'Heavy stone shuts the mausoleum around a small central space. Dust lies in the joints of the memorial surfaces, and age has softened the sharper edges of the masonry. The cool, mineral air holds no trace of domestic life. Here, even an ordinary shift of weight sounds like an interruption.')
exact('Gravesend Bay', 'Broad folds of `cwater`x cross Gravesend Bay, breaking reflected shapes into long, wavering fragments. The open reach keeps a deeper color beyond the nearest ripples. Salt hangs in the air, and the overlapping movement conceals the contours of the bay beneath a surface that never settles long enough to read.')
exact('Willow Cove', "A sheltered crescent of `ysand`x gives Willow Cove a close, quiet scale. Shell chips and tiny pebbles collect in shallow bands, their pale edges worn smooth. Finer grains soften older impressions between them. It's a shore of small details, where the curve of the cove keeps the open coast from feeling quite so vast.")
exact('Sidney Beach', "The `ysand of Sidney Beach`x spreads in broad, low ridges, pale shell fragments scattered among the grains. Passing feet have compressed narrow stretches into firmer ground, but the edges already look loose and uncertain. There's little enclosure here, only the exposed shore and the faint salt smell caught close to the sand.")
exact('Underlook Beach', 'Coarse `ysand`x and dark pebbles give Underlook Beach a rough, speckled surface. Worn shell pieces hide among the stones, and finer grains collect in the shallow hollows between them. The shore has a scraped, weathered look, with older tracks surviving as little more than softer patches in the gritty ground.')
exact('Badwater Park', "Worn patches break the `ggrass`x of Badwater Park into uneven islands. Tough weeds thrive along the margins, and old stems form a dry thatch beneath the greener blades. It's a neighborhood green with the polish rubbed off: open ground, stubborn growth, and room for company to make a little use of both.")
exact("Rosie's Diner", "Chrome edging curls around the long `wcounter`x at Rosie's, dulled where elbows have rested through countless cups of coffee. Upholstered `wbooths`x make snug alcoves beside the dining floor. The room smells of old coffee and the faint sweetness of syrup, with scuffs between the seats tracing the diner's familiar little journeys.", ('counter', "The counter's edge has been polished smooth by resting hands. Small scratches cloud the top, leaving a comfortable shared surface for leaning in to talk or examining something laid between companions."), ('booths', "Upholstered benches face across compact tables, their cushions softened along the most-used places. The raised backs shelter each group from the room's wider bustle, making a small pocket for close conversation."))
exact('the mayor\'s office', "A broad `wdesk`x gives the mayor's office a clear center of authority. The visitor chairs face a surface rubbed smooth at the working edge, while carefully finished wood lends the room a dry polish smell. Small marks of use survive beneath the formality, reminders that decisions here are still made at an ordinary conversational distance.", ('desk', "The working edge of the desk is smooth beneath the hands, with fine scratches crossing the surface. A visitor's chair faces it at an easy speaking distance, leaving the desktop between the two sides of a conversation."))
exact('the planetarium', 'The dome curves over rows of `wviewing seats`x, leaving few straight lines for the eye to settle on. Upholstery muffles the small sounds of company getting comfortable. Even between presentations, the room turns attention upward, where the great enclosed sweep has the waiting emptiness of a sky before the first stars appear.', ('viewing seats', 'The seats tip attention toward the planetarium dome. Padded backs and worn armrests make room to settle in, with the broad viewing space held comfortably above the seated company.'))
exact('the Bowling Lanes of The Alley', 'Long, polished lanes draw parallel lines through The Alley. Fine marks cross the approaches, and the wood carries a faint, waxy smell beneath the trace of well-used footwear. The `wsofa`x sits behind the lanes, close enough for companions to watch a turn and make their opinions comfortably known.', ('sofa', "Deep cushions settle into familiar hollows along the sofa. The arms are rubbed smooth, and the upholstery holds a faint fabric warmth; there's room to sit close or claim a comfortable corner."))
exact('the Arcade Hall of The Alley', "Arcade cabinets crowd The Alley's game hall in rows of bold artwork and rubbed edges. Finger marks have dulled the most handled panels, while dust finds narrow seams between the machines. The central aisle leaves room for company to hover behind a player, surrounded by the bright promises of the cabinet faces.")
exact('the Beelzebubbles Laundromat', 'Round-fronted machines line Beelzebubbles like a row of blunt, glassy eyes. Irreverent decoration competes with the scuffs on the walls, and the air smells thickly of detergent and warm fabric. A long `wfolding counter`x cuts through the clutter, the surface smooth enough to sort a load or lean across for gossip.', ('folding counter', 'The broad counter smells faintly of clean fabric and detergent. The finish is smooth enough for folding, with a long clear edge where companions can lean while sorting a load or sharing the latest gossip.'))
exact('the lighthouse stairs', "The lighthouse stairs curl tightly inside the masonry. Countless climbs have worn hollows into the treads, leaving dust in the angles beyond a shoe's reach. The stone carries a cool mineral smell, and each movement acquires a short echo as the stair winds around the same enclosing wall.")
exact('the beacon', "Glass and metal gather around the lighthouse beacon's central housing. Fine ridges in the optical assembly catch stray reflections, breaking nearby shapes into slivers. Dust lies in the less accessible joints. The standing space feels cramped beside the apparatus, a small human margin around something built to be seen far away.")
exact('the old gallows', "The `wgallows`x rise in blunt, weathered timbers above a scarred platform. Age cracks run deep along the grain, and the most exposed edges have silvered. There's nothing ornamental about the frame. The bare wood and open space beneath it leave the purpose of the structure horribly easy to imagine.")
exact('the waters of life', "The `cwaters of life`x have a clarity that makes distance difficult to trust. Nearer ripples pass over depths that look almost within reach, then recede beyond any sensible measure. It's a beautiful, disquieting expanse, with no solid surface to interrupt the layered water or give the eye a dependable scale.")
exact('the center of Rhagost', "Heavy, time-worn surfaces gather around Rhagost's central space. The scale feels built for a settlement larger than the immediate gathering area, with the `wopen center`x giving the surrounding mass a point of reference.")
exact('the Mobious path', "The `wpath`x repeats with the stubborn familiarity of a dream revisited. A worn patch of ground, a bend in the enclosing shapes, another stretch that seems already passed: none offers a reliable landmark. It's all perfectly visible at close range, yet difficult to place in a sequence that makes sense.")
exact('the Goblin Market\'s Library', "Books crowd the Goblin Market's shelves in mismatched ranks. Some bindings look waxy, others fibrous; the gaps between them carry a dry, peculiar smell that ordinary paper doesn't quite explain. A `wreading table`x makes a small island of order among the volumes, though even the straightest stacks lean a little toward their neighbors.", ('reading table', 'Broad enough for open books, the table keeps a clear working surface among the shelves. Fine scratches and a dull polish mark the places where readers have leaned, with chairs close enough to compare a passage in low voices.'))
exact('the Fleshforming Clinic', "Smooth treatment surfaces interrupt the Goblin Market's rough construction with an almost offensive cleanliness. The `wconsultation chairs`x faces fittings rubbed free of every casual stain. Around that precise little island, the enclosure keeps the market's uneven grain, making the clinic look less comforting than carefully prepared.", ('consultation chairs', 'Closely placed chairs face the consultation setting. Their spacing encourages a quieter voice, with a little room between the seats for company to turn toward one another without entering the working space.'))
exact('Arcane Dueling Circle', 'Circular markings define the `wdueling ground`x, their lines interrupted by old scuffs. Near the middle, repeated contests have worn a duller patch into the surface. The circle edge leaves observers room to gather, with the marked boundary making every step into the open ground feel deliberate.')
exact('the Alchemical Labratory', "Fixed racks crowd the laboratory's working surfaces. Old spills have left overlapping stains that cleaning has faded without erasing, and a sharp, mineral smell clings to the fittings. The `wworkbench`x keeps a clear station among them, bringing the room's strange experiments down to the scale of careful hands.", ('workbench', 'Fine tool marks cross the stout working surface, with dust caught in the deepest cuts. The bench stands at a practical height for leaning over a piece of work, bringing careful hands and curious company together.'))
exact('the Magical Workshop', 'Inscribed surfaces border the workshop, their elaborate patterns interrupted by ordinary scratches and old repairs. Fine dust settles into the deeper cuts. A central `wworktable`x gives arcane craft a practical meeting place, with enough room for company to lean together over work that has required both patience and precision.', ('worktable', 'A broad working surface bears fine cuts, stains, and older repairs. The edge is rubbed smooth where people lean over a project, with enough room for companions to examine the same detail from either side.'))
exact('the Engineering Workshop', 'Metal brackets and squared surfaces give the workshop a stubbornly practical geometry. Filing marks cloud the edges of the `wworkbench`x, and fine debris catches in the joints despite repeated cleanups. The air carries a dry metal smell, with each worn station recording the small adjustments of things made to fit.', ('workbench', 'Fine tool marks cross the stout working surface, with dust caught in the deepest cuts. The bench stands at a practical height for leaning over a piece of work, bringing careful hands and curious company together.'))
exact('the Folly', 'Mismatched woodwork and patched furnishings make the Folly feel assembled through a succession of small rescues. Old finishes meet without quite agreeing in color. A pair of `wcorner seats`x tucks against the irregular wall, the seats close enough for low conversation over the faint smells of fabric, dust, and familiar timber.', ('corner seats', 'These seats tuck into a quieter corner, angled toward one another. The fabric is softened by use, and the close arrangement makes it easy to lower a voice without losing sight of the room.'))
exact('the Court room', "The room's formal arrangement faces the raised judicial area. `wPublic benches`x stand in orderly rows, with clear floor separating the observers from the focus of proceedings.", ('public benches', 'Rows of substantial benches face the judicial area. Their seats and upper rails are smoothed by years of waiting, with enough space for neighboring spectators to exchange a quiet remark.'))
exact('the crematorium', "Heat has darkened the masonry around heavy furnace housings. Metal edges carry the dull wear of repeated handling, while fine residue catches in joints beyond an ordinary cleaning. The open floor remains starkly clear before the machinery. It's an orderly room, made more severe by how little the surroundings leave to explain.")
exact('a room full of body drawers', "Banks of metal-fronted body compartments line the morgue. Small handles repeat along the walls with a precision made uneasy by their purpose. A narrow central aisle divides the ranks, smelling faintly of cleaned metal. Scuffs on the floor provide almost the only irregularity in the room's measured arrangement.")
exact('a room full of clocks', 'Clock faces crowd the walls in overlapping circles, their numerals differing in size and style. Brass-colored edges sit beside darker cases, and fine dust gathers on the smallest ledges. The central floor feels almost accidental within this accumulation of measured time, a patch of room the clocks have yet to claim.')
exact('the Cortex Academy of Civic Integration Biodome airlock', 'Close metal panels enclose a compact transition chamber. Hard seals and repeated structural seams distinguish the airlock from the planted environment it serves.')
exact('the Gravesend History Museum - Prehistoric Gravesend', "Earth-toned display panels and stone-textured mounts organize this gallery around Gravesend's distant past. The viewing area leaves room to pause before the exhibits without crowding their edges.")
exact('the Gravesend History Museum - The Duncan Foundation', 'Formal display groupings present the Duncan Foundation within a restrained gallery. The viewing area is arranged for close attention to the exhibit panels and their careful sequence.')
exact('the Gravesend Historical Museum - Maritime Trade & Commerce', "Maritime display motifs and carefully separated exhibits trace the town's relationship with shipping. The viewing area allows the gallery's rope, wood, and hull-shaped details to be taken in at a measured pace.")
exact('the Gravesend Historical Museum - The Founding of Gravesend', "A sequence of historical panels gives this gallery a deliberate narrative shape. The viewing area faces displays devoted to Gravesend's beginnings, with restrained finishes keeping attention on the material presented.")
exact('the Gravesend History Museum - Modern Day Gravesend', "Contemporary display panels organize the gallery around the town's more recent identity. Clean edges frame the exhibits, with a viewing area allowing visitors to pause over the details.")
exact('the Gravesend History Museum - The Aquarium', 'Thick viewing panels separate the gallery from the water-filled displays. Their layered reflections give the room an unusual depth, with a viewing area set back from the glass.')

# Additional functions used by the civic, agricultural, dream, and travel maps.
rule(r'\b(?:park|farmland|green|valley|hills|hill|crop|cornfield|potato|tomato|carrot)\b', 'Low growth covers the worked and open ground. Soil shows between the plants, with the uneven texture of stems and leaves defining the surface.')
rule(r'\b(?:lot|rubble|ruins|remains|ruined|burnt|shattered)\b', 'Broken remnants interrupt a rough expanse of ground. Grit fills the gaps between larger fragments, and weather has dulled the exposed edges to similar shades. Older shapes remain just legible beneath the debris, giving the place the unsettled appearance of something interrupted and left to wear away.')
rule(r'\b(?:stables?|barn|hen house|pig pen|chicken run|row of stalls|grain silo)\b', 'Worn timber and practical partitions enclose a close agricultural space. Straw catches along the lower edges, mingling with the rich, earthy smell of old bedding. The clearest ground follows the working route between the fittings, rubbed bare by the repeated chores of tending the enclosure.')
rule(r'channel', 'Water occupies a narrow channel, the surface caught between enclosing banks. Silt traces soft lines along the margins, gathering in sheltered pockets. Small disturbances travel along the confined reach before fading into the overlapping patterns farther away.')
rule(r'dumpster|dumpsters', 'Dented refuse containers crowd a stained patch of ground. Old runoff has dried in dark fans beneath them, and stray scraps catch against the lower edges. The sour smell of discarded things lingers stubbornly here, even where the surrounding surface has been swept clear.')
rule(r'fence|railing', 'A boundary of repeated uprights divides the space. Weather has picked at the joints, while the most handled sections show a smoother, darker wear. Grit collects along the base, tracing the line between the well-used ground and the less disturbed surface beyond it.')
rule(r'baseball|first base|second base|third base|home base|foul line|pitcher|short stop|dash (?:to|home)|athletics|sport facilities|basketball|volleyball|skating|ice rink', 'The playing surface opens between the boundaries of the sporting ground. Repeated use has marked familiar lines of movement, with the busiest patches showing the deepest wear. The sidelines provide a shared vantage point, close enough to follow a game without crowding the field of play.')
rule(r'\b(?:massage|spa|beauty|treatment)\b', 'Muted colors surround the treatment space, carrying a faint trace of clean fabric and scented preparations. Small divisions give the room a private scale. A padded `wchaise`x sits at the margin, with room to settle away from the central working area and let the ordinary pace of movement slow.', ('chaise', "A padded chaise follows the length of the body, the upholstery softly creased from use. The raised end offers a comfortable place to rest a shoulder, with the treatment room's activity set slightly apart."))
rule(r'\b(?:art room|colour palette|smash room|repair|workplace)\b', 'Fine marks of work cover the `wworktable`x, layering careful scratches over older stains. The surrounding surfaces hold the dry smell of materials handled and set aside. Clear patches among the working areas leave room for company to examine a project without crowding the hands doing it.', ('worktable', 'A broad working surface bears fine cuts, stains, and older repairs. The edge is rubbed smooth where people lean over a project, with enough room for companions to examine the same detail from either side.'))
rule(r'book nook|children.s corner|comics section|librarian.s desk', 'Close shelves gather around a `warmchair`x, their contents making uneven bands of color. Paper lends the corner a dry, familiar smell. From the seat, the larger room gives way to the small scale of bindings, pages, and whatever has been brought here to read.', ('armchair', "The armchair's cushions have settled into a comfortable hollow. Worn arms support an elbow or an open book, and the fabric softens the small sounds of shifting into a more comfortable position."))
rule(r'arcade|pool tables|jungle gym|winding tubes|tube slide|playground', 'The recreation fittings break the space into bright details and worn edges. Years of repeated use have polished the nearest surfaces while leaving dust in the awkward corners. A gathering area sits clear of the activity space, giving companions somewhere to pause and watch between turns.')
rule(r'\b(?:breakroom|break room|community room|leisure hub|vip|v\.i\.p|private area|brothel|bordello|club|the dive|lodge)\b', 'Comfortable seats gather into a `wsofa`x, with a little room left between the furniture for passing company. The upholstery carries the faint smell of fabric warmed by use. Small worn patches lend the interior the easy familiarity of a place where people settle without ceremony.', ('sofa', "Deep cushions settle into familiar hollows along the sofa. The arms are rubbed smooth, and the upholstery holds a faint fabric warmth; there's room to sit close or claim a comfortable corner."))
rule(r'\b(?:hall|halls|passage|second floor|third floor|mezzanine|antechamber|east end|west end|wing|wings)\b', "A worn strip of floor carries passage through the building's interior. Old scuffs cluster along the lower walls, with repairs showing as slightly different shades in the finish. Voices and footsteps travel readily through the plain space, reaching farther than a casual glance.")
rule(r'\b(?:tower|clocktower|clock face|clock face|beacon|spire|spires)\b', 'The structure narrows around a small elevated space. Seams and worn edges show clearly in the surrounding construction, with fine dust caught beyond the usual reach of a hand. Up here, the close fittings make the height feel tangible even before attention turns beyond them.')
rule(r'\b(?:attic|loft)\b', 'The upper structure presses close around a dusty floor. Old timber and sheltered surfaces carry a dry, settled smell, and small debris has worked into the seams. The cramped margins give the loft a forgotten intimacy, like a pocket left above the ordinary business of the building.')
rule(r'mausoleum|morgue|dead|grave', "Heavy surfaces enclose a space given over to the dead. Fine marks of age interrupt the otherwise restrained finish, and the air carries a cool, mineral stillness. The open ground feels deliberately spare, leaving little to draw attention away from the room's solemn purpose.")
rule(r'security|interrogation|interview|detective bureau|observation|reprogramming', 'A plain `wtable`x separates the facing seats. Small scratches mar the working surface, and the surrounding fittings have a durable, institutional finish. The room leaves few places for an eye to wander; even an ordinary conversation becomes deliberate across the clear space between the chairs.', ('table', 'Chairs face one another across a plain, substantial tabletop. Small scratches soften the finish near the edges, leaving the middle clear for whatever the conversation places between the seated company.'))
rule(r'gas station|gas pumps|drive.through|driveway|off.ramp', 'Tire marks sweep across a patchwork of worn pavement and older repairs. Fine grit collects beyond the busiest lines of traffic, carrying a faint petroleum smell. The broad vehicle approach is scuffed where people slow, turn, or wait before moving on.')
rule(r'airport|port|depot|station|terminal', 'Repeated arrivals have worn the public floor smooth. A `wwaiting bench`x borders the clear passage, with seats marked by luggage and brief rests. The space carries the impersonal, familiar smell of a travel terminal, built around the pause between one journey and the next.', ('waiting bench', 'The bench has a smooth seat and a back marked by the rub of countless coats. From here, arrivals remain in view while the busiest line across the floor passes a little farther away.'))
rule(r'gazebo|gazeebo|pavilion|overlook|beacon point', 'An open-sided structure frames a small place to pause. Weather has roughened the exposed edges, while sheltered surfaces retain a smoother finish. The scale draws nearby company together without closing out the surrounding air, leaving the outlook as much a part of the space as the structure itself.')
rule(r'\b(?:maze|labyrinth)\b', "Enclosing boundaries break the ground into a sequence of close turns. Worn patches look unhelpfully alike, each stretch offering another variation on the same confined view. It's easy to take in the immediate space and harder to hold an impression of how it fits the whole.")
rule(r'\b(?:mine|mines|sublevels|hole|pit)\b', 'Raw ground falls within heavy surrounding walls of earth and stone. Loose fragments collect at the base, their fresh edges pale against older, darker surfaces. The air has a sheltered mineral smell, and the confined space makes each displaced chip sound larger than it looks.')
rule(r'\b(?:room|chamber|chambers|suite|suites|trailer|cabin|appartment|estate|hideout|hideaway|lair|alcove)\b', 'A modest floor lies within close surrounding walls. Small scuffs and old repairs give the plain surfaces a history of ordinary use. The margins offer a little privacy from the open middle, bringing anyone sharing the room within easy conversational distance.')
rule(r'fire pit|firepit|bonfire', 'Blackened remnants mark the `wfire pit`x, with pale ash tucked among the darker pieces. An old smoke smell clings to the immediate ground. The gathering area circles the scorched center at a comfortable distance, shaped by earlier company lingering beside the fire.')
rule(r'butcher|curing|meat|seafood|produce|bakery|grocery|snacks|cold drinks|sundries|lingerie|attire|firearms|defence|defense|cosmetics|hygiene|live bait', 'Practical displays border a narrow display aisle. Repeated cleaning has dulled the surfaces nearest the goods, and the surrounding fittings carry small marks of handling. The arrangement brings everything down to browsing distance, leaving room for a companion to pause alongside the displays.')
rule(r'bank|vault', 'Substantial fittings surround a clear public floor. The finish is restrained and carefully maintained, with wear most apparent where visitors wait. Hard edges and deliberate spacing lend the room a guarded formality, as though every ordinary movement is expected to happen in the proper place.')
rule(r'city|district|downtown|sprawl|neighborhood|neighbourhood|territory', 'Worn paving passes among close urban surfaces. Repairs overlap in different shades, and grime traces the places sheltered from an ordinary cleaning. Small marks of daily use give the built surroundings a lived-in texture, turning the open ground into another familiar piece of the city.')
rule(r'mist|fog|portal|godrealm|the other|the wilds|^hell$', "The surrounding space gathers into soft, uncertain layers. Nearer textures seem clear until attention settles on them; farther details dissolve before they suggest a dependable distance. It's a place with the uneasy familiarity of a dream, where even an ordinary patch of ground seems difficult to remember.")
rule(r'castle|palace|keep|throne', 'Substantial walls rise around a broad central floor. Age shows in the joints and the gently softened edges of the grander fittings. The scale lends a formal weight to anyone standing here, making an ordinary crossing of the room feel briefly like an entrance before an audience.')
rule(r'\b(?:street|road|way|run)\b', TERRAIN[1])

exact('The Gravesend History Museum - Possible food place?', 'Plain walls enclose a spare room in the museum. The open floor and unadorned surfaces give it the restrained character of an unused gallery annex; no exhibits or dining fittings occupy the space.')
exact('The Gravesend History Museum - Extra Space', "A spare gallery space lies within the museum's structure. The uncluttered floor and plain display walls make the room feel quiet and spacious, with no exhibits occupying the center.")
exact('the dismal Devilwood McDonald\'s', 'Bright corporate colors sit uneasily against scuffed flooring and worn plastic trim. A `wservice counter`x faces the dining space, where `wbooths`x form compact alcoves along the edge of the room.', ('service counter', 'The service counter has a smooth front edge and a scatter of small handling marks across the top. The customer side leaves room to lean beside a companion while taking in the room beyond.'), ('booths', "Upholstered benches face across compact tables, their cushions softened along the most-used places. The raised backs shelter each group from the room's wider bustle, making a small pocket for close conversation."))
exact("'Lucky Garden #3' at The Strip", 'Compact tables and simple decorative panels give Lucky Garden #3 a practical dining layout. A `wcorner table`x sits against the wall, with clear floor between the dining groups.', ('corner table', 'The corner table sits beyond the busiest line through the room. Chairs tuck close around a surface marked by faint rings and tiny scratches, making a comfortable pocket for an unhurried conversation.'))
exact("'The Glaze' at The Strip", "A glazed `wdisplay counter`x gives the small bakery the focus. Pale surfaces and compact furnishings frame a pair of `wcorner seats`x set back from the shop's central floor.", ('display counter', 'The glazed display counter catches nearby shapes in layered reflections. The public edge is smooth beneath resting hands, giving companions a shared position from which to examine the display.'), ('corner seats', 'These seats tuck into a quieter corner, angled toward one another. The fabric is softened by use, and the close arrangement makes it easy to lower a voice without losing sight of the room.'))
exact("'Close Knit Duds' at The Strip", 'Folded textiles and hanging displays give Close Knit Duds a soft, layered texture. A browsing aisle runs between the clothing displays, with room to stop beside their edges.')
exact("'Five and Under' at The Strip", "Compact displays gather everyday small goods into close-set rows. The store's bright, economical fittings face a scuffed customer aisle.")
exact("'Risque & Rebellious' at The Strip", 'Contrasting fabrics and bold display forms give the boutique a theatrical edge. A browsing area lies between the clothing arrangements, where layered textures crowd the eye.')
exact('Collateral Damage - Lyceum of the Mists', "A `wstudy table`x forms the center of this quieter part of Collateral Damage. Close shelving and restrained arcane motifs set the room apart from the premises' utilitarian retail spaces.", ('study table', 'The table leaves room for open books and elbows without crowding the seated company. Fine scratches catch across the working surface, a quiet record of readers leaning in over difficult passages.'))
exact('Collateral Damage - Victorious Secret', 'Carefully separated displays present this department with unusual discretion. Heavy trim connects it to Collateral Damage, while the `wconsultation chairs`x provides a less exposed place to pause.', ('consultation chairs', 'Closely placed chairs face the consultation setting. Their spacing encourages a quieter voice, with a little room between the seats for company to turn toward one another without entering the working space.'))
exact('the Owl\'s Post', 'Small compartments and paper-handling surfaces organize the postal interior. A `wsorting counter`x provides the central working edge, with clear floor in front for arrivals.', ('sorting counter', "The counter spreads beneath the sorting compartments, the finish rubbed smooth by paper and passing hands. The clear edge leaves room for companions to lean together beside the day's small business."))
exact('the printing press', 'Heavy metal framing surrounds the press assembly. Rollers, plates, and fixed housings form a dense mechanical shape beside a clear working area, with traces of ink settled into the older seams.')
exact('the grain silo', 'Curving storage walls rise around a confined central space. Fine grain dust settles into the seams, emphasizing the tall, enclosed shape of the agricultural structure.')
exact('the pig pen', 'Low agricultural boundaries enclose packed, churned ground. Straw fragments and worn timber give the pen a rough texture, with the center more heavily disturbed than the edges.')
exact('a chicken run', 'A simple enclosure surrounds scratched earth. Small depressions and scattered straw interrupt the ground, with the boundary giving the chicken run the close, practical shape.')
exact('the horse stable', 'Timber partitions divide the stable into close stalls beside a worn aisle. Straw catches along the lower rails, lending the enclosure a dry sweetness beneath the richer smell of old bedding. Knots and tooth-like chips break the grain of the wood, recording years of restless occupants and familiar chores.')
exact('the tomato stakes', 'Rows of slender stakes rise from worked soil. Tied stems and rough leaves gather around their supports, giving the crop a repeated vertical pattern amid the lower ground.')
exact('the cornfield', 'Corn stalks stand in close rows, their long `gleaves`x overlapping into ragged screens. Fine dust lies along the central veins, and dry edges have curled into narrow ribbons. Between the plants, worked earth forms shallow tracks that disappear quickly behind the next press of growth.')
exact('the carrot crop', 'Fine, divided carrot foliage spreads low over worked earth. The planted rows remain visible as repeated bands of green above the darker soil.')
exact('the potato patch', 'Low, leafy potato plants gather over mounded soil. Uneven ridges divide the cultivated patch, with loose earth showing between the thickening leaves.')
exact('the airlock of the Cortex Academy of Civic Integration biodome', EXACT['the cortex academy of civic integration biodome airlock'][0])
exact('the rooftop of a double-wide trailer', 'Seamed roofing panels form the narrow upper span of the trailer. The exposed surface follows the simple rectangle of the home below, with patches and weathered joints interrupting the metal.')
exact('The Void', 'An unbounded `cvoid`x surrounds a single point of awareness. There is no wall or floor to measure it against, only the strange impression that the emptiness is close enough to touch.')
exact('Creation', 'A pale, undefined space gathers around a clear center. The edges remain soft and unresolved, giving this place of beginnings the `cquiet expectancy`x of a form not yet chosen.')
exact('Time-Out', 'Plain walls and an uncluttered floor enclose a small, quiet room. The empty center and restrained surfaces give the space an air of deliberate separation from the activity beyond it.')
exact('Movement and Helpfiles', "Simple teaching panels border an open practice floor. The room's uncluttered proportions leave space to become familiar with movement, while a reading area offers a quiet place beside the instructional displays.")

from room_landmarks import install
install(exact, rule, TERRAIN)
from room_interiors import install as install_interiors
install_interiors(exact)
