// Generated by tools/generate_room_defaults.py; edit room_catalogue.py.
#ifndef HAVEN_ROOM_DEFAULT_TEXT_H
#define HAVEN_ROOM_DEFAULT_TEXT_H
static const char *const room_terrain_text[] = {
  "A plain floor meets unadorned walls around a clear central space. The\n\rrestrained surroundings leave little to distract from anyone sharing the room.`x\n\r",
  "`wWorn pavement`x forms the road surface, it's patched seams and scuffed edges\n\rrecording years of traffic. The traveled ground stays open between the rougher\n\rmargins.`x\n\r",
  "Plastered walls enclose a modest domestic interior. A scuffed floor leaves a\n\rclear central area, with the quieter edges of the room set apart from the\n\rspace used for passing through.`x\n\r",
  "A broad `wdance floor`x occupies the middle of the club. Dark finishes soften\n\rthe surrounding walls, while a seating area sits back from the open floor.`x\n\r",
  "Dining tables divide the room into small islands of conversation. Wipe-clean\n\rsurfaces and well-worn chair legs give the dining area a practical, familiar\n\rcharacter.`x\n\r",
  "Rows of displays organize the shop floor, leaving space to browse between\n\rthem. A `wcounter`x marks the edge of the customer area; scuffs near it's base\n\rshow where people linger.`x\n\r",
  "A long `wbar counter`x anchors the room, it's worn edge smoothed by countless\n\relbows. Tables occupy the remaining floor, with space between them for small\n\rgroups to gather.`x\n\r",
  "Hard walls hem in a strip of scuffed paving. Grit collects along the edges of\n\rthe `walley`x, where the ground receives less wear than the narrow middle.`x\n\r",
  "Broad spans of industrial flooring lie beneath structural beams. Scratches and\n\rold handling marks break up the plain surfaces, giving the open warehouse\n\rspace a thoroughly practical character.`x\n\r",
  "Durable flooring and plain walls give this commercial interior an orderly\n\rappearance. The center remains open, with the margins arranged to keep people\n\rout of the main circulation space.`x\n\r",
  "`gGrass`x covers the open ground in uneven layers. Shorter growth marks the\n\rmore exposed patches, while the thicker edges gather fallen stems and seed\n\rhusks.`x\n\r",
  "Rough `wstonework`x encloses the tunnel. Worn seams run along it's sides, and\n\rgrit gathers where the walls meet the floor; the confined space makes nearby\n\rmovement sound close.`x\n\r",
  "Small tables bring the cafe down to the scale of a quiet conversation. A\n\r`wcounter`x faces the seating area, with hard flooring worn smooth where\n\rcustomers gather.`x\n\r",
  "Seams and patches break up the exposed roof surface. The building's broad\n\rupper span provides little enclosure, and it's weathered materials show the\n\rwear of an elevated position.`x\n\r",
  "The building's lower structure is exposed here in heavy walls and a plain\n\rfloor. Corners feel close beneath the ceiling, and small sounds carry through\n\rthe enclosed basement.`x\n\r",
  "Hard, washable surfaces define the clinical space. Pale walls and an\n\runcluttered floor give the room a deliberate order, with an edge of antiseptic\n\rin the air.`x\n\r",
  "Restrained finishes and durable flooring lend the public interior a formal\n\rair. The broad central space leaves room for people to wait without crowding\n\rthe margins.`x\n\r",
  "Upholstered seats fit tightly within the vehicle's metal body. The compact\n\rpassenger space carries the familiar smells of fabric, rubber, and enclosed\n\rtravel.`x\n\r",
  "The `cair`x stretches around an unbounded space above the ground. There is no\n\rfloor or surrounding wall here; distance and height give the emptiness it's\n\rscale.`x\n\r",
  "Irregular ground gathers around the `rhellgate`x, it's edges harsh against the\n\rsurrounding space. The threshold dominates the scene, making everything close\n\rto it feel provisional.`x\n\r",
  "`cWater`x fills the surrounding expanse, it's overlapping surface textures\n\rconcealing the depth beneath. There is no solid footing in this stretch of\n\ropen water.`x\n\r",
  "Water encloses the space on every side. Suspended particles soften it's depth,\n\rand the `bsubmerged surroundings`x merge into an indistinct distance.`x\n\r",
  "A vast reach of `cupper air`x surrounds this exposed height. With no enclosing\n\rsurfaces, the space has the disorienting scale of open atmosphere.`x\n\r",
  "`gTree trunks`x crowd the uneven forest floor. Roots break through a layer of\n\rold leaves and fallen twigs, while overlapping branches divide the woodland\n\rinto close, irregular spaces.`x\n\r",
  "Uneven `wrock`x forms the cave's walls and floor. Natural seams interrupt the\n\rstone, and loose fragments collect in shallow pockets along it's base.`x\n\r",
  "Soft mud lies between tangled roots and coarse wetland growth. Dark water\n\roccupies the lower patches of the `gswamp`x, breaking the ground into\n\runcertain pieces.`x\n\r",
  "Loose `ysand`x forms a broad, yielding surface. Finer grains collect between\n\rscattered shell fragments, while the exposed ground bears faint ridges and\n\rworn depressions.`x\n\r",
  "Broken `wstone`x and rough outcrops interrupt the ground. Thin deposits of\n\rgrit settle in the cracks, leaving the harder surfaces exposed and uneven\n\runderfoot.`x\n\r",
  "`cShallow water`x spreads over a submerged bed of sediment. The bottom remains\n\rclose beneath the surface, it's texture softened by layers of water and fine\n\rsilt.`x\n\r",
  "A strip of `wsidewalk`x provides firm footing. It's paving is worn through the\n\rmiddle, with seams and small chips collecting grit along the less-traveled\n\redges.`x\n\r",
  "A broad parking surface opens around worn bay markings. Tire scuffs and\n\rpatched pavement distinguish the vehicle spaces from the rougher margins of\n\rthe lot.`x\n\r",
  "Rows of `wgrave markers`x interrupt the cemetery ground. Their stone surfaces\n\rvary in wear, while the spaces between them lend the burial ground a measured,\n\rsolemn rhythm.`x\n\r",
  "Compacted `yearth`x forms the traveled ground. Small stones press into it's\n\rsurface, and looser soil gathers along the edges where fewer feet have passed.`x\n\r",
};
static const char *const room_realm_forest_text[] = {
  "Ancient `gtrees`x rise from a deep mat of roots and moss. Their immense trunks\n\rcrowd unfamiliar plants, whose curling leaves and intricate shapes make the\n\rforest seem almost recognizable, yet never quite familiar.`x\n\r",
  "Widely spaced `gtrees`x rise above soft grass and naturally ordered flower\n\rbeds. Their clean-limbed shapes give the woodland a strange composure, as\n\rthough each trunk had grown with room deliberately left for it's neighbors.`x\n\r",
  "Massive `gtrunks`x rise through tangled undergrowth. Thick roots buckle the\n\rsoil, and layers of vines and fallen timber turn the forest floor into a\n\rdense, muscular tangle.`x\n\r",
  "Knotted `wtrees`x twist above a litter of splintered branches. Swollen burls\n\rsuggest faces in the bark, and the interlocking trunks break the forest into\n\rcramped, unsettling pockets.`x\n\r",
};
static const char *const room_transit_text[] = {
  "Hard panels enclose a compact subway carriage. Metal handholds border a narrow\n\rstanding aisle, while a line of `wseats`x occupies the edge of the passenger\n\rspace.`x\n\r",
  "A narrow `wseat`x defines the riding position. The space is open to it's\n\rsurroundings, with little enclosure between the rider and the passing\n\renvironment.`x\n\r",
  "A worn strip of `yearth`x lies among close-set forest trunks. Roots interrupt\n\rthe path surface, and fallen leaves collect along the less-traveled margins\n\rbeneath the branches.`x\n\r",
};
#endif
