#ifndef HAVEN_TERRITORY_REWARDS_H
#define HAVEN_TERRITORY_REWARDS_H
// One reward per territory. Zero denotes a blank reward or a potion-only territory.
struct TerritoryRewardDefault { const char *name; int primary, secondary; };
static const TerritoryRewardDefault territory_reward_defaults[] = {
  {"Montreal, Canada", 1, 0},
  {"Toronto, Canada", 2, 0},
  {"Vancouver, Canada", 13, 0},
  {"New York, New York", 18, 0},
  {"New York", 6, 0},
  {"Boston, Massachusetts", 19, 0},
  {"London, England", 5, 0},
  {"Edinburgh, Scotland", 15, 0},
  {"Miami, Florida", 3, 0},
  {"Belfast, Ireland", 4, 0},
  {"New Orleans, Louisiana", 14, 0},
  {"Richmond, Virginia", 8, 0},
  {"Yellowstone, Wyoming", 16, 0},
  {"Austin, Texas", 7, 0},
  {"Las Vegas, Nevada", 20, 0},
  {"Los Angeles, California", 21, 0},
  {"Mexico City, Mexico", 9, 0},
  {"Bogota, Columbia", 12, 0},
  {"Brasilia, Brazil", 57, 0},
  {"Lima, Peru", 22, 0},
  {"Cordoba, Argentina", 23, 0},
  {"Dublin, Ireland", 24, 0},
  {"Paris, France", 25, 0},
  {"Madrid, Spain", 26, 0},
  {"Paris, France", 25, 0},
  {"Berlin, Germany", 27, 0},
  {"Milan, Italy", 28, 0},
  {"Rome, Italy", 29, 0},
  {"Athens, Greece", 30, 0},
  {"Warsaw, Poland", 31, 0},
  {"Stockholm, Sweden", 10, 0},
  {"Oslo, Norway", 17, 0},
  {"Helsinki, Finland", 60, 0},
  {"Bucharest, Romania", 32, 0},
  {"Kiev, Ukraine", 33, 0},
  {"Minsk, Belarus", 34, 0},
  {"Moscow, Russia", 35, 0},
  {"Saint Petersburg, Russia", 36, 0},
  {"Istanbul, Turkey", 58, 0},
  {"Jerusalem, Israel", 11, 0},
  {"Damascus, Syria", 0, 0},
  {"Baghdad, Iraq", 59, 0},
  {"Astana, Kazakhstan", 62, 0},
  {"Ulaanbaatar, Mongolia", 37, 0},
  {"Novosibirsk, Russia", 0, 0},
  {"Beijing, China", 56, 0},
  {"Shanghai, China", 61, 0},
  {"Mumbai, India", 38, 0},
  {"Bangkok, Thailand", 39, 0},
  {"Seoul, South Korea", 40, 0},
  {"Kyoto, Japan", 41, 0},
  {"Tokyo, Japan", 42, 0},
  {"Jakarta, Indonesia", 43, 0},
  {"Sydney, Australia", 44, 0},
  {"Melbourne, Australia", 45, 0},
  {"Perth, Australia", 46, 0},
  {"Alice Springs, Australia", 47, 0},
  {"Auckland, New Zealand", 0, 0},
  {"Christchurch, New Zealand", 48, 0},
  {"Cairo, Egypt", 0, 0},
  {"Marrakesh, Morocco", 49, 0},
  {"Niamey, Niger", 0, 0},
  {"Khartoum, Sudan", 63, 0},
  {"Lusaka, Zambia", 0, 0},
  {"Gaborone, Botswana", 0, 0},
  {"Cape Town, South Africa", 0, 0},
  {"Dynasty, China", 50, 0},
  {"Hand, Russia", 51, 0},
  {"Yerevan, Armenia", 0, 0},
  {"Merida, Mexico", 0, 0},
  {"Westrend", 0, 0},
  {"Navorost", 52, 0},
  {"Gharrek", 0, 0},
  {"Navvere", 53, 0},
  {"Northgard", 0, 0},
  {"Anupharis", 0, 0},
  {"Rhagost", 0, 0},
  {"Lauriea", 0, 0},
  {"Nissenia", 0, 0},
  {"Celestriana", 0, 0},
  {"Hong Kong, China", 54, 0},
  {"District 82", 0, 0},
  {"Haven", 55, 0},
};
#endif
